package presentacion;

import javax.swing.JOptionPane;
import logicaNegocio.Participante;
import presentacion.controladores.MesaJugadorControlador;
import presentacion.vistas.VistaMesaJugador;


/**
 *
 * @author digregor
 */
public class VentanaMesaJugador extends javax.swing.JFrame implements VistaMesaJugador {

    private MesaJugadorControlador controlador;

    /**
     * Creates new form NewJFrame
     */
    public VentanaMesaJugador(Participante participanteActual) {
        initComponents();
        iniciarEscuchador();
        controlador = new MesaJugadorControlador(participanteActual, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        r = new presentacion.PanelRuleta();
        labelSaldoJugador = new javax.swing.JLabel();
        labelRonda = new javax.swing.JLabel();
        labelNombreJugador = new javax.swing.JLabel();
        labelUltimoNumSorteado = new javax.swing.JLabel();
        labelNumSorteado = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelValorOcurrencia = new javax.swing.JLabel();
        btnAbandonar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaRondasJugador = new javax.swing.JList<>();
        labelRondasJugador = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaValorOcurrencia = new javax.swing.JList<>();
        btnFicha1 = new javax.swing.JButton();
        btnFicha5 = new javax.swing.JButton();
        btnFicha10 = new javax.swing.JButton();
        btnFicha50 = new javax.swing.JButton();
        btnFicha100 = new javax.swing.JButton();
        labelNroRonda = new javax.swing.JLabel();
        labelMesa = new javax.swing.JLabel();
        labelNroMesa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelSaldoJugador.setText("SaldoJugador");

        labelRonda.setText("Ronda:");

        labelNombreJugador.setText("NombreJugador");

        labelUltimoNumSorteado.setText("UlNumSor");

        labelNumSorteado.setText("Numero Sorteado: ");

        labelValorOcurrencia.setText("Valor    |    Ocurrencia   ");

        btnAbandonar.setText("Abandonar");

        listaRondasJugador.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaRondasJugador);

        labelRondasJugador.setText("Ronda   |   Total apostado   |   Ganado   |   Perdido   |   Balance    ");

        listaValorOcurrencia.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaValorOcurrencia);

        btnFicha1.setBackground(new java.awt.Color(204, 204, 204));
        btnFicha1.setText("1");
        btnFicha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFicha1ActionPerformed(evt);
            }
        });

        btnFicha5.setBackground(new java.awt.Color(0, 204, 0));
        btnFicha5.setText("5");
        btnFicha5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFicha5ActionPerformed(evt);
            }
        });

        btnFicha10.setBackground(new java.awt.Color(0, 102, 204));
        btnFicha10.setText("10");
        btnFicha10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFicha10ActionPerformed(evt);
            }
        });

        btnFicha50.setBackground(new java.awt.Color(255, 153, 102));
        btnFicha50.setText("50");
        btnFicha50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFicha50ActionPerformed(evt);
            }
        });

        btnFicha100.setBackground(new java.awt.Color(255, 51, 51));
        btnFicha100.setText("100");
        btnFicha100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFicha100ActionPerformed(evt);
            }
        });

        labelNroRonda.setText(" ");

        labelMesa.setText("Ruleta:");

        labelNroMesa.setText(" ");
        labelNroMesa.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRondasJugador)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelValorOcurrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 148, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAbandonar))))
                    .addComponent(jSeparator1)
                    .addComponent(r, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFicha1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFicha5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFicha10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFicha50, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFicha100, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(labelNumSorteado)
                        .addGap(18, 18, 18)
                        .addComponent(labelUltimoNumSorteado, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelSaldoJugador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelMesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNroMesa)
                        .addGap(45, 45, 45)
                        .addComponent(labelRonda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNroRonda)
                        .addGap(245, 245, 245)
                        .addComponent(labelNombreJugador)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRonda)
                    .addComponent(labelSaldoJugador)
                    .addComponent(labelNombreJugador)
                    .addComponent(labelNroRonda)
                    .addComponent(labelMesa)
                    .addComponent(labelNroMesa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumSorteado)
                    .addComponent(labelUltimoNumSorteado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFicha1)
                    .addComponent(btnFicha50)
                    .addComponent(btnFicha100)
                    .addComponent(btnFicha10)
                    .addComponent(btnFicha5))
                .addGap(20, 20, 20)
                .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAbandonar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelValorOcurrencia, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelRondasJugador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFicha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFicha1ActionPerformed
        controlador.almacenarFicha(1);
    }//GEN-LAST:event_btnFicha1ActionPerformed

    private void btnFicha5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFicha5ActionPerformed
        controlador.almacenarFicha(5);
    }//GEN-LAST:event_btnFicha5ActionPerformed

    private void btnFicha10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFicha10ActionPerformed
        controlador.almacenarFicha(10);
    }//GEN-LAST:event_btnFicha10ActionPerformed

    private void btnFicha50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFicha50ActionPerformed
        controlador.almacenarFicha(50);
    }//GEN-LAST:event_btnFicha50ActionPerformed

    private void btnFicha100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFicha100ActionPerformed
        controlador.almacenarFicha(100);
    }//GEN-LAST:event_btnFicha100ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbandonar;
    private javax.swing.JButton btnFicha1;
    private javax.swing.JButton btnFicha10;
    private javax.swing.JButton btnFicha100;
    private javax.swing.JButton btnFicha5;
    private javax.swing.JButton btnFicha50;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelMesa;
    private javax.swing.JLabel labelNombreJugador;
    private javax.swing.JLabel labelNroMesa;
    private javax.swing.JLabel labelNroRonda;
    private javax.swing.JLabel labelNumSorteado;
    private javax.swing.JLabel labelRonda;
    private javax.swing.JLabel labelRondasJugador;
    private javax.swing.JLabel labelSaldoJugador;
    private javax.swing.JLabel labelUltimoNumSorteado;
    private javax.swing.JLabel labelValorOcurrencia;
    private javax.swing.JList<String> listaRondasJugador;
    private javax.swing.JList<String> listaValorOcurrencia;
    private presentacion.PanelRuleta r;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void mostrarMensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
    private void iniciarEscuchador() {
        r.agregar(new PanelRuleta.Escuchador() {
            @Override
            public void celdaSeleccionada(int universalCellCode) {
                controlador.apostar(universalCellCode);
            }
        });
    }

    @Override
    public void actualizarNroRonda(int nro) {
        labelNroRonda.setText("#" + String.valueOf(nro));
    }

    @Override
    public void habilitarPantallaMesa() {
        r.reanudar();
    }

    @Override
    public void inhabilitarPantallaMesa() {
        r.pausar();
    }

    @Override
    public void mostrarNroMesa(int nro) {
        labelNroMesa.setText("#" + String.valueOf(nro));
    }

    @Override
    public void mostrarUltimoNroSorteado(int ultimoNum) {
        labelUltimoNumSorteado.setText(String.valueOf(ultimoNum));
    }
    
    @Override
    public void mostrarSaldoActual(int saldo) {
        labelSaldoJugador.setText("$" + String.valueOf(saldo));
    }

    @Override
    public void mostrarValorApostado(int cellCode, int monto) {
        r.setApuesta(cellCode, monto);
    }

    @Override
    public void limpiarValoresApostados() {
        r.limpiar();
    }
}
