package componentes;

import java.awt.Component;
import java.util.List;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import logicaNegocio.Casillero;
import logicaNegocio.Crupier;
import logicaNegocio.Efecto;
import logicaNegocio.Mesa;
import logicaNegocio.Sesion;
import logicaNegocio.TipoApuesta;
import servicios.Fachada;
import servicios.Observable;
import servicios.Observador;

/**
 *
 * @author digregor
 */
public class VentanaMesaCrupier extends javax.swing.JFrame implements Observador {

    private Sesion sesion;
    private Crupier crupier;
    private Mesa mesa;
    int apuestaRojo = 0;

    /**
     * Creates new form NewJFrame
     */
    public VentanaMesaCrupier(Sesion sesionActual) {
        initComponents();
        this.sesion = sesionActual;
        this.crupier = (Crupier) sesionActual.getUsuario();
        this.mesa = crupier.getMesa();
        mesa.subscribir(this);
        inicializar();
        // Escuchador para el caso de jugador
        //escuchador();
    }
    
    private void inicializar() {
        r.desactivarBotones();
        popularComboEfectos();
        habilitarTiposApuesta();
        this.labelNroRuleta.setText("Ruleta #" + mesa.getNroMesa());
    }
    
    private void habilitarTiposApuesta() {
        for (TipoApuesta tipoApuesta : this.mesa.getTiposApuesta()) {
            this.habilitarCasilleros(tipoApuesta.getCasillerosDisponibles());
        }
    }
    
    private void habilitarCasilleros(List<Casillero> listaCasilleros) {
        for (Casillero casillero : listaCasilleros) {
            r.habilitar(casillero.getCellCode(), true);
        }
    }
    
    private void popularComboEfectos() {
        List<Efecto> efectos = Fachada.getInstancia().getEfectos();
        for (Efecto efecto : efectos) {
            comboEfectos.addItem(efecto);
        }
        comboEfectos.setRenderer(new EfectoRenderer());
    }
    
    private void escuchador() {
//        r.agregar(new PanelRuleta.Escuchador() {
//                @Override
//                public void celdaSeleccionada(int universalCellCode) {
//                    int apuesta = Integer.valueOf(jTextField1.getText());
//                    System.out.println("Id de celda seleccionada: " + universalCellCode + ". Apuesta anterior: " + r.getApuesta(universalCellCode) + ". Apuesta nueva:" + apuesta);
//                    r.setApuesta(universalCellCode, apuesta);
//                }
//            });
    }

    @Override
    public void actualizar(Observable origen, Object evento) {
        if (evento.equals(Evento.MESA_PAUSADA)) {
            r.pausar();
            labelUltimoNro.setText(String.valueOf(mesa.getUltimoNumeroSorteado()));
        } else if (evento.equals(Evento.RONDA_LIQUIDADA)) {
            r.reanudar();
        }
    }
    
    private class EfectoRenderer implements ListCellRenderer<Efecto> {
        
        private DefaultListCellRenderer defaultRenderer = new DefaultListCellRenderer();

        @Override
        public Component getListCellRendererComponent(JList list, Efecto efecto, int index, boolean isSelected, boolean cellHasFocus) {
            JLabel efect = new JLabel();
            efect.setText((efecto.getNombreEfecto()));
            return efect;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        r = new componentes.PanelRuleta();
        labelNroRuleta = new javax.swing.JLabel();
        btnCerrarMesa = new javax.swing.JButton();
        btnLanzarPagar = new javax.swing.JButton();
        labelCantApuestas = new javax.swing.JLabel();
        labelValorTotalApuestas = new javax.swing.JLabel();
        comboEfectos = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        labelBalanceCasa = new javax.swing.JLabel();
        labelRonda = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaJugadores = new javax.swing.JList<>();
        labelUltimosLanzamientos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaRondas = new javax.swing.JList<>();
        labelUltimoNro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNroRuleta.setText("jLabel1");

        btnCerrarMesa.setText("Cerrar mesa");
        btnCerrarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarMesaActionPerformed(evt);
            }
        });

        btnLanzarPagar.setText("Lanzar/Pagar");
        btnLanzarPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanzarPagarActionPerformed(evt);
            }
        });

        labelCantApuestas.setText("jLabel1");

        labelValorTotalApuestas.setText("jLabel1");

        comboEfectos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboEfectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEfectosActionPerformed(evt);
            }
        });

        labelBalanceCasa.setText("jLabel1");

        labelRonda.setText("jLabel2");

        listaJugadores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listaJugadores);

        labelUltimosLanzamientos.setText("Ultimos lanzamientos:");

        listaRondas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaRondas);

        labelUltimoNro.setText("Ultimo n° sorteado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCantApuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(labelValorTotalApuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addComponent(comboEfectos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLanzarPagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelUltimoNro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelBalanceCasa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelRonda)
                        .addGap(182, 182, 182)
                        .addComponent(labelNroRuleta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCerrarMesa))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelUltimosLanzamientos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRonda)
                    .addComponent(labelNroRuleta)
                    .addComponent(btnCerrarMesa)
                    .addComponent(labelBalanceCasa))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCantApuestas)
                    .addComponent(labelValorTotalApuestas)
                    .addComponent(comboEfectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLanzarPagar)
                    .addComponent(labelUltimoNro))
                .addGap(18, 18, 18)
                .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUltimosLanzamientos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarMesaActionPerformed

    private void btnLanzarPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanzarPagarActionPerformed
        // Llamar a un metodo y no implementarlo dentro del boton
        Efecto efectoSeleccionado = (Efecto) comboEfectos.getSelectedItem();
        this.mesa.accionarMesa(efectoSeleccionado);
    }//GEN-LAST:event_btnLanzarPagarActionPerformed

    private void comboEfectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEfectosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEfectosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarMesa;
    private javax.swing.JButton btnLanzarPagar;
    private javax.swing.JComboBox comboEfectos;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelBalanceCasa;
    private javax.swing.JLabel labelCantApuestas;
    private javax.swing.JLabel labelNroRuleta;
    private javax.swing.JLabel labelRonda;
    private javax.swing.JLabel labelUltimoNro;
    private javax.swing.JLabel labelUltimosLanzamientos;
    private javax.swing.JLabel labelValorTotalApuestas;
    private javax.swing.JList<String> listaJugadores;
    private javax.swing.JList<String> listaRondas;
    private componentes.PanelRuleta r;
    // End of variables declaration//GEN-END:variables
}
